### ISSUE TITLE
Custom type colorized

### ISSUE THREAD

**Issue by Wtheodoro** [thanos-theme/visual-studio-code#2]
<img width="480" alt="Screen Shot 2022-08-03 at 12 34 04" src="https://user-images.githubusercontent.com/64755624/182649458-5e2a8e81-0f6e-490b-be14-432c52536630.png">

What if, the custom types in TS had different colors? like de base types.

**Comment by arthur404dev** [comment]
This will be featured on the next release. 

Thanks for the feedback :)
