### ISSUE TITLE
highlights na barra de rolagem vertical

### ISSUE THREAD

**Issue by durvalcarvalho** [thanos-theme/visual-studio-code#4]
Antes de qualquer coisa, muito legal o tema! Gostei muito da paleta de cores.

Uma coisa que senti falta foi a o highlights na barra de rolagem vertical. Eu uso muito esse highlights quando estou revisando código antes de comitar para encontrar os trechos de códigos que foram modificados.

Segue os prints do tema `solarized dark` que tem o hightlight que estou falando, e o print do `thanos-theme` que não tem.

![image](https://user-images.githubusercontent.com/31013187/183112340-31f7a360-55a6-4969-ad8e-a74da9104f3c.png)
![image](https://user-images.githubusercontent.com/31013187/183112385-8dfb63c9-26e3-4477-a2b7-0bde1e3c0edb.png)

**Comment by arthur404dev** [comment]
Vou adicionar essa feature no próximo release! Obrigado pelo feedback, de verdade !

**Comment by arthur404dev** [comment]
Por mais que eu goste muito de manter todas as cores próximas da cor base do tema optei por utilizar a convenção para o DiffEditor e utilizar as cores verde e vermelha do tema para melhor destacar as diferenças.

Preview da nova versão com as mudanças sugeridas no seu issue: 

![arthur404dev-jfUMLj32tX](https://user-images.githubusercontent.com/59490008/186056985-933c0db9-32a9-4d19-a811-7dfd28305595.png)
